#pragma once

#include "renderer/RendererStats.hpp"

#include <cstdint>
#include <memory>

namespace vshade::asset { class AssetManager; }
namespace vshade::renderer { class Camera; }

namespace vshade::scene {

class Scene;

/** @brief Resolves and submits camera, model, sprite, light, and debug scene data. */
class SceneRenderer final {
public:
    explicit SceneRenderer(asset::AssetManager& assets);
    ~SceneRenderer();

    SceneRenderer(const SceneRenderer&) = delete;
    SceneRenderer& operator=(const SceneRenderer&) = delete;
    SceneRenderer(SceneRenderer&&) noexcept;
    SceneRenderer& operator=(SceneRenderer&&) noexcept;

    /** @brief Renders through the highest-priority active camera; false if none exists. */
    bool render(Scene& scene, std::uint32_t viewportWidth, std::uint32_t viewportHeight);

    /** @brief Returns the camera generated by the most recent successful render. */
    [[nodiscard]] const renderer::Camera* activeCamera() const noexcept;

    /** @brief Aggregated snapshot from the most recent scene render. */
    [[nodiscard]] const renderer::DebugFrameStats& frameStats() const noexcept;

private:
    struct Impl;
    std::unique_ptr<Impl> m_impl;
};

} // namespace vshade::scene
